Testing for new refactorying style
PkHutch/CSC207H1SProject pull request #116
Opened 2017-03-29 16:47 UTC by hansenchen66

2017-03-29 17:17 UTC, hansenchen66 commented
fixes #112 #111 #110 #109

2017-03-31 18:04 UTC, PkHutch requested changes

2017-03-31 18:04 UTC, PkHutch commented on src/Main.java
> +		EntityCommand[] commands = new EntityCommand[] { new OrderCommand(faxmachine), new PickerCommand(warehouse) };
Over line limit.

2017-03-31 18:04 UTC, PkHutch commented on src/Main.java
>  		System.out.println("The current state of warehouse has been saved");
The Warehouse hasn't been saved, the Warehouse is beginning the process of being saved.

2017-04-01 06:15 UTC, PkHutch requested changes

2017-04-01 06:15 UTC, PkHutch commented on src/entities/Level.java
> +	public void setSku(Integer sku) {
This should not exist, the SKU never changes.

2017-04-01 08:35 UTC, closed without merging